---
groups:
- type: "STANDING_ORDER"
- type: "RECURRENT_INCOME"
- name: "LEBENSMITTEL"
  type: "CUSTOM"
  whitelistMatcher:
  - "UKAT = 'LEBENSMITTEL'"
- name: "TANKSTELLE"
  type: "CUSTOM"
  whitelistMatcher:
  - "SPEZ = 'TANKSTELLE'"
- name: "BARGELDABHEBUNG"
  type: "CUSTOM"
  whitelistMatcher:
  - "UKAT = 'BARGELDABHEBUNG'"
- name: "KREDITKARTE"
  type: "CUSTOM"
  whitelistMatcher:
  - "UKAT = 'KREDITKARTENABRECHNUNG'"
- name: "SHOPPING"
  type: "CUSTOM"
  whitelistMatcher:
  - "UKAT = 'SHOPPING'"
- type: "RECURRENT_SEPA"
  blacklistMatcher:
  - "GID = 'LU96ZZZ0000000000000000058'"
  - "IBAN = 'DE88500700100175526303'"
  - "GID = 'DE94ZZZ00000561653'"
  - "GID = 'DE24ZZZ00000561652' AND NOT VWZ LIKE '%AMAZON%PRIME%GE%BUEHR%'"
  - "GID = 'DE78ZZZ00000561650'"
  - "GID = 'DE51ZZZ00000561651'"
  - "GID = 'DE96ZZZ00000594888'"
  - "GID = 'DE39DBV00000002177' AND VWZ LIKE '%FAHRSCHEIN%'"
  - "VWZ LIKE '%OFFLINE%' OR VWZ LIKE '%TERMINAL%' OR VWZ LIKE '%KART%ZAHL%'"
  - "RFN LIKE 'EC%' OR RFN LIKE '%ELV%ME%' OR RFN LIKE '%KART%ZAHL%'"
  - "VWZ LIKE 'EC%' OR VWZ LIKE '%ELV%ME%' OR VWZ LIKE '%KART%ZAHL%'"
  - "RFN LIKE '%ELV%' AND VWZ LIKE '%ME%'"
  - "HKAT = 'PRIVAT'"
  - "UKAT = 'KREDITKARTENABRECHNUNG'"
  - "SPEZ = 'SONDERTILGUNG'"
- type: "RECURRENT_NONSEPA"
  blacklistMatcher:
  - "HKAT = 'PRIVAT'"
  - "VWZ LIKE '%OFFLINE%' OR VWZ LIKE '%TERMINAL%' OR VWZ LIKE '%KART%ZAHL%'"
  - "RFN LIKE 'EC%' OR RFN LIKE '%ELV%ME%' OR RFN LIKE '%KART%ZAHL%'"
  - "VWZ LIKE 'EC%' OR VWZ LIKE '%ELV%ME%' OR VWZ LIKE '%KART%ZAHL%'"
  - "RFN LIKE '%ELV%' AND VWZ LIKE '%ME%'"
  - "UKAT = 'KREDITKARTENABRECHNUNG'"
- name: "OTHER_INCOME"
  type: "OTHER_INCOME"
- name: "OTHER_EXPENSES"
  type: "OTHER_EXPENSES"
recurrentWhiteListMatcher:
- "(RFN LIKE '%CLUB%' AND NOT RFN LIKE '%NACHT%CLUB%') OR (VWZ LIKE '%CLUB%' AND NOT VWZ LIKE '%NACHT%CLUB%')"
- "SPEZ = 'MITGLIEDSCHAFT'"
- "UKAT = 'VERSICHERUNGEN'"
- "((RFN LIKE '%DEUTSCH%BAHN%' OR RFN LIKE '%DB%VERTRIEB%') AND VWZ LIKE '%BAHNCARD%') OR ((RFN LIKE '%DEUTSCH%BAHN%' OR RFN LIKE '%DB%VERTRIEB%') AND (VWZ LIKE '%7081%4110%' OR VWZ LIKE '%7081%4101%' OR VWZ LIKE '%7081%4200%'))"
- "RFN LIKE '%ABONNEMENT%' OR VWZ LIKE '%ABONNEMENT%' OR VWZ LIKE '% ABOS %' OR VWZ LIKE '% ABO %' OR RFN LIKE '% ABOS %' OR RFN LIKE '% ABO %'"
- "RFN LIKE '%JAHRES%TICKET%' OR VWZ LIKE '%JAHRES%TICKET%'"
- "RFN LIKE '%JAHRES%' OR VWZ LIKE '%JAHRES%'"
- "RFN LIKE '% GEB%HR %' OR VWZ LIKE '% GEB%HR %'"
- "RFN LIKE '%BEITRAG %' OR VWZ LIKE '%BEITRAG %'"
- "RFN LIKE '%POLICE %' OR VWZ LIKE '%POLICE %'"
- "RFN LIKE '%XING%' AND VWZ LIKE '%PREMIUM%' "
- "VWZ LIKE '%KFZ%STEUER%'"
